### ISSUE TITLE
Country

### ISSUE THREAD

**Issue by Kadantte** [mathdroid/covid19#1]
Is there a way from the API that lets us get Data about one Country?
I want to deploy the API but let it just show Data about my Country atm!

**Comment by mathdroid** [comment]
Just read this, working on it.

**Comment by mathdroid** [comment]
Just updated the service with a few new endpoints:

- [/api/countries](https://covid19.mathdro.id/api/countries): Lists all countries and ISO codes

- /api/countries/[country] e.g. https://covid19.mathdro.id/api/countries/Indonesia, https://covid19.mathdro.id/api/countries/USA, https://covid19.mathdro.id/api/countries/CN: shows summary of a specific country

- /api/countries/[country]/confirmed e.g.https://covid19.mathdro.id/api/countries/USA/confirmed: lists regions of a country, sorted by confirmednumber, desc

- /api/countries/[country]/recovered e.g.https://covid19.mathdro.id/api/countries/USA/recovered: lists regions of a country, sorted by recovered number, desc

- /api/countries/[country]/deaths e.g.https://covid19.mathdro.id/api/countries/USA/deaths: lists regions of a country, sorted by deaths number, desc

![image](https://user-images.githubusercontent.com/3748658/76370010-1a775c00-6368-11ea-9431-6559ca8c069a.png)

**Comment by Kadantte** [comment]
Yea it's good now, thanks for doing that.
